module.exports = {
  Main: {
	    'LOAD_PROMOTIONS': 'LOAD_PROMOTIONS',
	    'LOAD_PROMOTIONS_SUCCESS': 'LOAD_PROMOTIONS_SUCCESS',
	    'LOAD_PROMOTIONS_FAIL': 'LOAD_PROMOTIONS_FAIL',
	    'LOAD_USER_PROMOTIONS': 'LOAD_USER_PROMOTIONS',
	    'LOAD_USER_PROMOTIONS_SUCCESS': 'LOAD_USER_PROMOTIONS_SUCCESS',
	    'LOAD_USER_PROMOTIONS_FAIL': 'LOAD_USER_PROMOTIONS_FAIL'
  }
};